openapi: 3.0.3
info:
  title: PetsShelters
  version: 1.0.0
  description: ''
servers:
  - url: http://localhost:80/api
    description: Developer edition
paths:
  /authorization/login:
    $ref: paths/authorization_login.yaml
  /authorization/callback:
    $ref: paths/authorization_callback.yaml
  /authorization/refresh:
    $ref: paths/authorization_refresh.yaml
  /authorization/user-info:
    $ref: paths/authorization_user-info.yaml
  /files/upload:
    $ref: paths/files_upload.yaml
  /shelters:
    $ref: paths/shelters.yaml
  /shelters/adopters:
    $ref: paths/shelters_adopters.yaml
  /shelters/adopters/{id}:
    $ref: paths/shelters_adopters_{id}.yaml
  /shelters/animals:
    $ref: paths/shelters_animals.yaml
  /shelters/animals/types:
    $ref: paths/shelters_animals_types.yaml
  /shelters/animals/{id}:
    $ref: paths/shelters_animals_{id}.yaml
  /shelters/employees:
    $ref: paths/shelters_employees.yaml
  /shelters/employees/{id}:
    $ref: paths/shelters_employees_{id}.yaml
  /shelters/locations:
    $ref: paths/shelters_locations.yaml
  /shelters/locations/cities:
    $ref: paths/shelters_locations_cities.yaml
  /shelters/locations/{id}:
    $ref: paths/shelters_locations_{id}.yaml
  /shelters/names:
    $ref: paths/shelters_names.yaml
  /shelters/{id}:
    $ref: paths/shelters_{id}.yaml
  /shelters/{id}/locations:
    $ref: paths/shelters_{id}_locations.yaml