http:
  addr: :80

logger:
  log_level: "debug"

postgres:
  db_url: ""

oauth:
  client_id: ""
  client_secret: ""
  state_lifetime: 300s
  web_redirect: ""

jwt:
  access_secret: "accesssecret"
  access_lifetime: 10m
  refresh_secret: "refreshsecret"
  refresh_lifetime: 30m

redis:
  addr: "redis:6379"
  password: "redispassword"

s3:
  region: "us-east-1"
  access_key: ""
  secret_key: ""
  endpoint: ""
  public_read_bucket: ""

mailjet:
  public_key: ""
  private_key: ""
  sender_email: ""
  sender_name: ""
  invitation_template_id: ""
  invitation_url: ""

temporary_files:
  scheduler_period: 1h
  lifetime: 1h

infrastructure:
  service_url: "http://localhost:80/api"
  webclient_url: "http://localhost:80"
  domain: "localhost"