http:
  addr: 'localhost:80'

logger:
  log_level: 'debug'

postgres:
  db_url: ''

oauth:
  client_id: ''
  client_secret: ''
  state_lifetime: 300s

jwt:
  access_secret: 'accesssecret'
  access_lifetime: 10m
  refresh_secret: 'refreshsecret'
  refresh_lifetime: 30m

redis:
  addr: "redis:6379"
  password: "redispassword"

domains:
  service: "http://localhost:80"
  webclient: "http://localhost:8090"